/**
 * Generates a GitHub Actions workflow that publishes a package using NPM Trusted
 * Publishing (OIDC). This is the artifact written to disk when a user confirms
 * a "Setup OIDC" event (Chapter 1.3.3, 8.5).
 *
 * Per Chapter 1.2.3 the generated content is reference-only: if the destination
 * file already exists we never overwrite it unless the user passes --force.
 */
import type { OidcContext } from '../shared/index.js';

export const OIDC_WORKFLOW_PATH = '.github/workflows/publish.yml';

export function renderPublishWorkflow(ctx: OidcContext): string {
  const branch = ctx.branch ?? 'main';
  return `# Generated by pnpm-pub. Reference-only configuration — edit to taste.
name: Publish

on:
  push:
    branches: [${branch}]
  workflow_dispatch:

# Trusted Publish (OIDC) — no long-lived NPM token required.
permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --provenance --access public
`;
}

/**
 * Decide whether we may write the workflow file. Returns a reason string when
 * blocked, or null when the write is allowed (Chapter 1.2.3 / 1.3.3).
 */
export function canWriteWorkflow(existing: boolean, force: boolean): string | null {
  if (existing && !force) {
    return 'A publish workflow already exists. Re-run with --force to overwrite.';
  }
  return null;
}
