import path from "node:path";
import { promises as fsp } from "node:fs";
import type { TrustedPublisherConfig } from "../shared/index.js";

export const OIDC_WORKFLOW_PATH = ".github/workflows/publish.yml";

export type WorkflowPreviewResult =
  | { ok: true; path: string; content: string; exists: boolean }
  | { ok: false; error: string };

function githubBranchFromWorkflowRef(file: string): string {
  const marker = "@refs/heads/";
  const index = file.indexOf(marker);
  if (index < 0) return "main";
  return file.slice(index + marker.length).split(":")[0] || "main";
}

function githubWorkflowFile(config: TrustedPublisherConfig): string | null {
  if (config.type !== "github") return null;
  const file = config.claims.workflow_ref.file.trim();
  return file || OIDC_WORKFLOW_PATH;
}

export function renderPublishWorkflow(config: TrustedPublisherConfig): WorkflowPreviewResult {
  if (config.type !== "github") {
    return { ok: false, error: "Only GitHub Actions trusted publishers can generate a GitHub workflow." };
  }
  const workflowFile = githubWorkflowFile(config) ?? OIDC_WORKFLOW_PATH;
  const branch = githubBranchFromWorkflowRef(workflowFile);
  const environment = config.claims.environment ?? "release";
  const content = `# Generated by pnpm-pub. Reference-only configuration; edit to taste.
name: Publish

on:
  push:
    branches: [${branch}]
  workflow_dispatch:

# Trusted Publishing (OIDC) requires id-token: write and no long-lived npm token.
permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${environment}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --provenance --access public
`;
  return { ok: true, path: OIDC_WORKFLOW_PATH, content, exists: false };
}

export async function previewPublishWorkflow(
  packagePath: string,
  config: TrustedPublisherConfig,
): Promise<WorkflowPreviewResult> {
  const rendered = renderPublishWorkflow(config);
  if (!rendered.ok) return rendered;
  const workflowPath = path.join(packagePath, rendered.path);
  const exists = await fileExists(workflowPath);
  return { ...rendered, path: workflowPath, exists };
}

export async function writePublishWorkflow(
  packagePath: string,
  config: TrustedPublisherConfig,
  force = false,
): Promise<WorkflowPreviewResult> {
  const preview = await previewPublishWorkflow(packagePath, config);
  if (!preview.ok) return preview;
  if (preview.exists && !force) {
    return { ok: false, error: "A publish workflow already exists. Confirm overwrite before writing." };
  }
  await fsp.mkdir(path.dirname(preview.path), { recursive: true });
  await fsp.writeFile(preview.path, preview.content, "utf8");
  return { ...preview, exists: true };
}

async function fileExists(file: string): Promise<boolean> {
  try {
    await fsp.access(file);
    return true;
  } catch {
    return false;
  }
}
